{
 "title": "SSLO Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_clickhouse", "label": "Clickhouse", "query": "grafana-clickhouse-datasource" },
   {
    "name": "device_name",
    "label": "Device Hostname",
    "query": "SELECT DISTINCT(hostname) from \"otel\".\"sslo_logs\""
   },
   {
    "name": "sslo_host",
    "label": "SSLO Hostname",
    "query": "SELECT DISTINCT(sslo_host) from \"otel\".\"sslo_logs\""
   },
   {
    "name": "virtual_server",
    "label": "Virtual Server",
    "query": "SELECT distinct(vip) from \"otel\".\"sslo_logs\""
   },
   { "name": "N", "label": "N", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Count Over Time - Destination IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfMinute(Timestamp) as bucketed_timestamp,\n  dst_ip,\n  count(dst_ip) as Value\nFROM \"otel\".\"sslo_logs\"\nWHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  (Timestamp >= $__fromTime AND Timestamp <= $__toTime)\nGROUP BY bucketed_timestamp, dst_ip\nORDER BY bucketed_timestamp DESC"
    }
   ]
  },
  {
   "title": "Avg Duration By Virtual Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfMinute(Timestamp) as bucketed_timestamp,\n  vip,\n  avg(duration) as Value\nFROM \"otel\".\"sslo_logs\"\nWHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  (Timestamp >= $__fromTime AND Timestamp <= $__toTime)\nGROUP BY bucketed_timestamp, vip\nORDER BY bucketed_timestamp DESC"
    }
   ]
  },
  {
   "title": "Avg Client Bytes In/Out By SSLO Hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfMinute(Timestamp) as bucketed_timestamp,\n  sslo_host,\n  avg(client_bytes_in) as In,\n  avg(client_bytes_out) as Out\nFROM \"otel\".\"sslo_logs\"\nWHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  (Timestamp >= $__fromTime AND Timestamp <= $__toTime)\nGROUP BY bucketed_timestamp, sslo_host\nORDER BY bucketed_timestamp DESC"
    }
   ]
  },
  { "title": "Trend Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Top N = ${N}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top ${N} Client IPs",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT src_ip, count(src_ip) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY src_ip ORDER by Value DESC  LIMIT ${N}"
    }
   ]
  },
  {
   "title": "Top ${N} Destination IPs",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT dst_ip, count(dst_ip) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY dst_ip ORDER by Value DESC  LIMIT ${N}"
    }
   ]
  },
  {
   "title": "Top ${N} Destination Hosts",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT sslo_host, count(sslo_host) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY sslo_host ORDER by Value DESC  LIMIT ${N}"
    }
   ]
  },
  {
   "title": "Top ${N} Destination Hosts",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT dst_port, count(dst_port) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY dst_port ORDER by Value DESC  LIMIT ${N}"
    }
   ]
  },
  { "title": "SSL Protocol / Ciphers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Client SSL Protocol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT client_ssl_protocol, count(client_ssl_protocol) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY client_ssl_protocol LIMIT 1000"
    }
   ]
  },
  {
   "title": "Client SSL Cipher",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT client_ssl_cipher, count(client_ssl_cipher) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY client_ssl_cipher LIMIT 1000"
    }
   ]
  },
  {
   "title": "Server SSL Protocol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT server_ssl_protocol, count(server_ssl_protocol) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY server_ssl_protocol LIMIT 1000"
    }
   ]
  },
  {
   "title": "Server SSL Cipher",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT server_ssl_cipher, count(server_ssl_cipher) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY server_ssl_cipher LIMIT 1000"
    }
   ]
  },
  { "title": "Other Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Decrypt Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT decryption_status, count(decryption_status) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY decryption_status  LIMIT 1000"
    }
   ]
  },
  {
   "title": "L7 Protocols",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT l7_protocol, count(l7_protocol) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY l7_protocol LIMIT 1000"
    }
   ]
  },
  {
   "title": "URL Categories",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT url_category, count(url_category) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY url_category LIMIT 1000"
    }
   ]
  },
  {
   "title": "Policy Rules",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT policy_rule, count(policy_rule) as Value FROM \"otel\".\"sslo_logs\" WHERE \n  (hostname = '${device_name}' OR '${device_name}' = 'all') AND\n  (sslo_host = '${sslo_host}' OR '${sslo_host}' = 'all') AND\n  (vip = '${virtual_server}' OR '${virtual_server}' = 'all') AND\n  ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )\nGROUP BY policy_rule LIMIT 1000"
    }
   ]
  }
 ]
}